# yaml-language-server: $schema=./.app-config.schema.yml
auth:
  firebase:
    clientConfig: '{}'
    secretKeyfile: '{}'
api:
  databaseUrl: 'postgresql://journals:curvenote@localhost:5432/journals_test?statement_cache_size=0'
  authCookieSecret: qwerty
  sessionSecret: qwerty
  analyticsSecret: qwerty
  handshakeSigningSecret: qwerty
  previewSigningSecret: qwerty
  jwtSigningSecret: qwerty
  checkSASecretKeyfile: '{}'
  storageSASecretKeyfile: '{}'
  privateCDNSigningInfo:
    'prv.curvenote.dev':
      hostname: qwerty
      keyName: qwerty
      key: qwerty
    'tmp.curvenote.dev':
      hostname: qwerty
      keyName: qwerty
      key: qwerty
  propertyPublicKey: QWERTY
  vercel:
    cron:
      secret: qwerty
app:
  extensions:
    pmc:
      airtable:
        apiKey: 'qwerty'
      inboundEmail:
        password: curvenote
      depositService:
        secretKeyfile: '{}'
    hhmi-compliance:
      airtable:
        apiKey: 'qwerty'
